### ISSUE TITLE
TYPO3 v10 Compatibility

### ISSUE THREAD

**Issue by flossels** [lightwerk/static_info_tables_nl#8]
Hi Achim,

any chance to get this extension ready for TYPO3 v10?

**Comment by achimfritz** [comment]
Hi Florian, i have pushed a feature/v10 branch. Can you confirm it runs proper on v10?

**Comment by flossels** [comment]
I'll check that.

**Comment by flossels** [comment]
Hi Achim,

Works like a charm. Just a small thing: After running the update script, an argument for the language label is missing.

![Bildschirmfoto 2020-08-10 um 18 05 42](https://user-images.githubusercontent.com/8256874/89805175-8a675980-db35-11ea-9a5c-85ac616c804b.png)

You can simply adjust [this line](https://github.com/lightwerk/static_info_tables_nl/blob/feature/v10/class.ext_update.php#L58) as follows:

`$content .= '<p>' . LocalizationUtility::translate('updateLanguageLabels', 'StaticInfoTables', ['static_info_tables_nl']) . '</p>';`

**Comment by achimfritz** [comment]
`+`
